### ISSUE TITLE
Agent : impossible to add initContainers, envVars and volumeMounts

### ISSUE THREAD

**Issue by alexis-petit-sonarsource** [OctoPerf/helm-charts#17]
Exact same issue as [14](https://github.com/OctoPerf/helm-charts/issues/14) but for the agent.
Keys concerned : 
- extraEnvVars
- volumeMounts
- extraInitContainers 

The same fix as [PR](https://github.com/OctoPerf/helm-charts/pull/16) could be used

**Comment by jloisel** [comment]
Done as in PR and released.

**Comment by QDudouet** [comment]
Hello, 
It seems that the problem still exists in version 13.2.1 of kubernetes-agent.
The Valuespath + "." part mentioned [here ](https://github.com/OctoPerf/helm-charts/issues/14)is available on version 13.2.0 but no longer on 13.2.1 on deployment.yaml file.
And we still have this error when deploying with 13.2.0 : **_Error: template: perfng-agent/charts/kubernetes-agent/templates/deployment.yaml:52:36: executing "perfng-agent/charts/kubernetes-agent/templates/deployment.yaml" at <.Values.extraInitContainers>: wrong type for value; expected string; got []interface {}_**
Maybe a general fix is ​​planned for v14.0.0 of the agent ?

**Comment by QDudouet** [comment]
> Done as in PR and released.

Hello,
It seems that the problem still exists in version 13.2.1 of kubernetes-agent.
The Valuespath + "." part mentioned https://github.com/OctoPerf/helm-charts/issues/14is available on version 13.2.0 but no longer on 13.2.1 on deployment.yaml file.
And we still have this error when deploying with 13.2.0 : Error: template: perfng-agent/charts/kubernetes-agent/templates/deployment.yaml:52:36: executing "perfng-agent/charts/kubernetes-agent/templates/deployment.yaml" at <.Values.extraInitContainers>: wrong type for value; expected string; got []interface {}
Maybe a general fix is ​​planned for v14.0.0 of the agent ?

**Comment by QDudouet** [comment]
> Done as in PR and released.

Hello,
It seems that the problem still exists in version 13.2.1 of kubernetes-agent.
The Valuespath + "." part mentioned https://github.com/OctoPerf/helm-charts/issues/14is available on version 13.2.0 but no longer on 13.2.1 on deployment.yaml file.
And we still have this error when deploying with 13.2.0 : **_Error: template: perfng-agent/charts/kubernetes-agent/templates/deployment.yaml:52:36: executing "perfng-agent/charts/kubernetes-agent/templates/deployment.yaml" at <.Values.extraInitContainers>: wrong type for value; expected string; got []interface {}_**
Maybe a general fix is ​​planned for v14.0.0 of the agent ?
